apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
  namespace: iput-kernel-foundation
data:
  SMTP_HOST: "mail"
  SMTP_PORT: "465"
  SMTP_USERNAME: "noreply@iput-kernel.com"

  REDIS_HOST: "account-worker"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  DB_HOST: "account-db"
  DB_USER: "root"
  DB_NAME: "account"
  DB_PORT: "5432"
  DB_SSLMODE: "require"