apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: iput-kernel-foundation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-pod
        image: ghcr.io/cirrus-ltd/moves-clone-auth:6ab042d
        ports:
        - containerPort: 8080