apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: iput-kernel-foundation
type: Opaque
data:
  SMTP_PASSWORD: {{ base64_encoded_smtp_password }}
  REDIS_PASSWORD: {{ base64_encoded_redis_password }}
  DB_PASSWORD: {{ base64_encoded_db_password }}