services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile.dev
    tty: true
    ports:
      - 1323:1323
    volumes:
      - ./:/app
    environment:
      - GO111MODULE=on
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 9999:80
    volumes:
      - pgadmin-data:/app/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/var/lib/redis/data
      - ./redis.conf:/etc/redis/redis.conf
    command: "/etc/redis/redis.conf"
    ports:
      - "6379"
    env_file:
      - .env

volumes:
  db-store:
  pgadmin-data:
  redis:
