services:
  account-app:
    image: account-app:latest
    ports:
      - 1323:50051
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - account-db
      - account-worker

  account-db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

  account-worker:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6379"

volumes:
  db-store:
  redis:
