services:
  account-app:
    build:
      context: .
    ports:
      - 1323:50051
      - 80:80
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  account-db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  account-worker:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6379"

volumes:
  db-store:
  redis:
