// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Follow struct {
	FollowingUserID pgtype.UUID        `json:"following_user_id"`
	FollowedUserID  pgtype.UUID        `json:"followed_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	RealName  pgtype.Text        `json:"real_name"`
	Birthday  pgtype.Date        `json:"birthday"`
	Sex       pgtype.Text        `json:"sex"`
	Phone     pgtype.Text        `json:"phone"`
	Describe  pgtype.Text        `json:"describe"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	ClassID      pgtype.UUID        `json:"class_id"`
	IsVerified   bool               `json:"is_verified"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VerifyEmail struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Email      string    `json:"email"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
