// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: renew_access_token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenewAccessTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefleshToken string `protobuf:"bytes,1,opt,name=reflesh_token,json=refleshToken,proto3" json:"reflesh_token,omitempty"`
}

func (x *RenewAccessTokenRequest) Reset() {
	*x = RenewAccessTokenRequest{}
	mi := &file_renew_access_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAccessTokenRequest) ProtoMessage() {}

func (x *RenewAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renew_access_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*RenewAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_renew_access_token_proto_rawDescGZIP(), []int{0}
}

func (x *RenewAccessTokenRequest) GetRefleshToken() string {
	if x != nil {
		return x.RefleshToken
	}
	return ""
}

type RenewAccessTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken          string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAt string `protobuf:"bytes,2,opt,name=access_token_expires_at,json=accessTokenExpiresAt,proto3" json:"access_token_expires_at,omitempty"`
}

func (x *RenewAccessTokenResponse) Reset() {
	*x = RenewAccessTokenResponse{}
	mi := &file_renew_access_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewAccessTokenResponse) ProtoMessage() {}

func (x *RenewAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renew_access_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*RenewAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_renew_access_token_proto_rawDescGZIP(), []int{1}
}

func (x *RenewAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RenewAccessTokenResponse) GetAccessTokenExpiresAt() string {
	if x != nil {
		return x.AccessTokenExpiresAt
	}
	return ""
}

var File_renew_access_token_proto protoreflect.FileDescriptor

var file_renew_access_token_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3e,
	0x0a, 0x17, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66,
	0x6c, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x72, 0x65, 0x66, 0x6c, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x74,
	0x0a, 0x18, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x35, 0x0a,
	0x17, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x70, 0x75, 0x74, 0x2d, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_renew_access_token_proto_rawDescOnce sync.Once
	file_renew_access_token_proto_rawDescData = file_renew_access_token_proto_rawDesc
)

func file_renew_access_token_proto_rawDescGZIP() []byte {
	file_renew_access_token_proto_rawDescOnce.Do(func() {
		file_renew_access_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_renew_access_token_proto_rawDescData)
	})
	return file_renew_access_token_proto_rawDescData
}

var file_renew_access_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_renew_access_token_proto_goTypes = []any{
	(*RenewAccessTokenRequest)(nil),  // 0: pb.RenewAccessTokenRequest
	(*RenewAccessTokenResponse)(nil), // 1: pb.RenewAccessTokenResponse
}
var file_renew_access_token_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_renew_access_token_proto_init() }
func file_renew_access_token_proto_init() {
	if File_renew_access_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_renew_access_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_renew_access_token_proto_goTypes,
		DependencyIndexes: file_renew_access_token_proto_depIdxs,
		MessageInfos:      file_renew_access_token_proto_msgTypes,
	}.Build()
	File_renew_access_token_proto = out.File
	file_renew_access_token_proto_rawDesc = nil
	file_renew_access_token_proto_goTypes = nil
	file_renew_access_token_proto_depIdxs = nil
}
