DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS verify_emails CASCADE;
DROP TABLE IF EXISTS transfers CASCADE;
DROP TABLE IF EXISTS statements CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TYPE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS thresholds CASCADE;